name: Build Executables

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install PyInstaller and dependencies
      run: |
        pip install pyinstaller
        # Install PyQt5 dependencies
        pip install PyQt5==5.15.9
    
    - name: Run tests
      run: |
        Write-Host "Running tests for all projects..."
        
        # 获取所有目录
        $directories = Get-ChildItem -Directory
        
        foreach ($dir in $directories) {
            $pyFiles = Get-ChildItem -Path $dir.FullName -Filter "*.py"
            
            if ($pyFiles.Count -gt 0) {
                Write-Host "=== Testing $($dir.Name) ==="
                
                # 切换到项目目录
                Set-Location $dir.FullName
                
                # 检查并安装依赖包
                if (Test-Path "requirements.txt") {
                    Write-Host "Installing dependencies from requirements.txt"
                    pip install -r requirements.txt
                }
                
                # 运行测试文件（如果存在）
                if (Test-Path "test_*.py") {
                    $testFiles = Get-ChildItem -Filter "test_*.py"
                    foreach ($testFile in $testFiles) {
                        Write-Host "Running test: $($testFile.Name)"
                        python $testFile.Name
                    }
                } else {
                    Write-Host "No test files found in $($dir.Name)"
                }
                
                # 返回上级目录
                Set-Location ..
            }
        }
    
    - name: Build all projects
      run: |
        Write-Host "Building all projects..."
        
        # 获取所有目录
        $directories = Get-ChildItem -Directory
        
        foreach ($dir in $directories) {
            $pyFiles = Get-ChildItem -Path $dir.FullName -Filter "*.py"
            
            if ($pyFiles.Count -gt 0) {
                Write-Host "=== Building $($dir.Name) ==="
                
                # 切换到项目目录
                Set-Location $dir.FullName
                
                # 检查并安装依赖包
                if (Test-Path "requirements.txt") {
                    Write-Host "Installing dependencies from requirements.txt"
                    pip install -r requirements.txt
                }
                
                # 查找主要的Python文件 (优先使用Qt版本)
                if (Test-Path "log_classifier_qt.py") {
                    # 检查是否有图标文件
                    $iconParam = ""
                    if (Test-Path "icon.ico") {
                        $iconParam = "--icon=icon.ico"
                    }
                    pyinstaller --onefile --name $dir.Name --windowed $iconParam --noconsole log_classifier_qt.py
                } elseif (Test-Path "main.py") {
                    pyinstaller --onefile --name $dir.Name --windowed --noconsole main.py
                } else {
                    # 使用第一个找到的Python文件
                    $firstPyFile = $pyFiles[0].Name
                    pyinstaller --onefile --name $dir.Name --windowed --noconsole $firstPyFile
                }
                
                # 返回上级目录
                Set-Location ..
            }
        }
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: |
          */dist/*.exe